export default {
    TIMESERIES_PICKLIST_UPDATE: "TIMESERIES_PICKLIST_UPDATE",
    TIMESERIES_PICKLIST_INIT: "TIMESERIES_PICKLIST_INIT",
    DATERANGE_PICKLIST_UPDATE: "DATERANGE_PICKLIST_UPDATE",
    DATERANGE_PICKLIST_INIT: "DATERANGE_PICKLIST_INIT"
};